docs/api/tileEngine.html
=> Minor corrections

doc-tasks.js, docs/api/animation.html, docs/api/assets.html, docs/api/core.html, docs/api/events.html, docs/api/gameLoop.html, docs/api/keyboard.html, docs/api/plugin.html, docs/api/pointer.html, docs/api/pool.html, docs/api/quadtree.html, docs/api/sprite.html, docs/api/spriteSheet.html, docs/api/store.html, docs/api/tileEngine.html, docs/api/vector.html, docs/download.html, docs/getting-started.html, docs/index.html, docs/made-with-kontra.html, docs/pages/download.js
`marked` v0.7.0 changed the classname of code from `lang-js` to `language-js`, which broke the code for the import tablist switcher output.
=> docs: fix doc import tablist switcher

src/vector.js, test/unit/vector.spec.js
=> fix(vector): keep clamp settings after adding two vectors

src/assets.js, src/events.js, test/unit/assets.spec.js
=> feat(assets): emit assetLoaded event for each asset loaded

src/tileEngine.js, test/unit/tileEngine.spec.js
On Safari 12.1.2 copying the offscreenCanvas into the real canvas doesn't seem to work. The offscreenCanvas is created correctly (as can be seen through the canvas debug tool) but when the render function is drawing the image that is in it, it has no effect. Creating a new image with the content of the offscreenCanvas and using that one instead seems to fix the problem.
=> Use temporary image for tileEngine renders

src/pool.js, test/unit/pool.spec.js
I refactored Pool a little to improve performance and usability.
The biggest change is that alive objects are now at the front of the pool. This simplifies the logic in various ways. Most disruptively by removing `_i` and using `size` instead. This changes `size` from how large the pool's array is to how many items are currently alive and stored in the pool. 
In `update()`, each item that was found to be dead was spliced to the front immediately. After running a few performance tests, I've replaced it with a system that sorts the pool at the end of `update()` if needed. A few more tests led me to believe that sorting only the alive part of the array was also faster (especially in mostly empty pools) so that's what I've done.
This is currently failing a test. Not wanting to just remove …
=> Pool Improvements

docs/api/animation.html, docs/api/assets.html, docs/api/keyboard.html, docs/api/pool.html, docs/api/sprite.html, docs/api/spriteSheet.html, docs/api/tileEngine.html, docs/getting-started.html, src/animation.js, src/assets.js, src/keyboard.js, src/pool.js, src/sprite.js, src/spriteSheet.js, src/tileEngine.js
I found a few URLs in the documentation that are broken because the anchor is behind a /. For example, the first link in the [SpriteSheet documentation](https://straker.github.io/kontra/api/spriteSheet). If you replace `/#` in the URLs with `#`, the links work.
I ran a regex on the src code comments to fix these errors.
=> Fix anchor URLs in documentation

src/tileEngine.js
I use an object layer to save the position of some elements, but when the tile engine tries to render it, it fails because the data property does not exist.
This was the simples fix I could think of. Let me know if there's a better fix for this.
=> When an object layer tries to be rendered, engine fails.

src/gameObject.js
Thank you for such amazing library. It has almost everything to get started with game development on JavaScript while keeping everything simple.
While testing extending a `GameObject`, and using groups, I noticed that the `dt` parameter was not passed to the children of the object. Even though the `dt` parameter is optional please consider to passed down to the object children for consistency.
Any feedback on the proposed fix is welcomed.
=> Passing dt to GameObject children update

examples/sprite/controllingASprite.html, src/keyboard.js, test/unit/keyboard.spec.js
Allow `#bindKeys` to specify which handler to bind callbacks to. Accepted parameters are `keydown` or `keyup`.
```js
kontra.bindKeys(['up', 'down', 'left', 'right'], function(e) {
console.log('key released: ', e)
}, 'keyup');
```
=> Add keyup support to bindKeys

src/gameLoop.js
`dt` will always be passed so this makes it less awkward to use for TypeScript.
=> fix(gameLoop): make "dt" always exist in update

src/button.js, test/unit/button.spec.js
Closes #241 
Allows buttons to be disabled when created by passing in a `disabled` property like so:
```js
let button = Button({
disabled: true
});
```
By default, the `disabled` property is `false`.
=> feat(button): button can be disabled when created

src/text.js, test/unit/text.spec.js
fixes #239 
Doesn't seem like the best `describe` block for the test but didn't want to be too invasive for this change
=> Cast value to string when setting Text.text

karma.debug.js, package.json, src/grid.js, test/unit/grid.spec.js, test/unit/pointer.spec.js
Also adds a way to debug tests in the browser using `npm run test:debug` (and fixes pointer tests to work in the browser debug view).
Closes #240
=> fix(grid): work with colSpan > 2

src/gameObject.js, test/unit/gameObject.spec.js
Discovered that gameObject world calculations did not correctly calculate rotation from parent. Also found that scale should be applied first before rotating.
=> fix(gameObject): correctly calculate world position when nested children are rotated

examples/galaxian/js/galaxian.js, examples/pointer/tracking.html, examples/scene/snake.js, examples/sprite/clampSpriteMovement.html, examples/sprite/controllingASprite.html, examples/tileEngine/camera/index.html, karma.conf.js, src/gamepad.js, src/gesture.js, src/input.js, src/keyboard.js, src/kontra.defaults.js, src/kontra.js, test/setup.js, test/typings/input.ts, test/unit/button.spec.js, test/unit/gameLoop.spec.js, test/unit/gamepad.spec.js, test/unit/input.spec.js, test/unit/keyboard.spec.js, test/unit/pointer.spec.js, test/utils.js
Closes #261
Also cleaned up duplicate `simulateEvent` code.
BREAKING CHANGE
=> feat(input): add input wraper api, rename `up`, `down`, `left`, `right` keyboard names to `arrowup`, `arrowdown`, `arrowleft`,  `arrowright`

.eslintrc.js, src/gameObject.js, src/plugin.js, src/pointer.js, src/scene.js, src/tileEngine.js, src/utils.js, test/integration/scene.spec.js, test/typings/scene.ts, test/unit/scene.spec.js
After some thought decided to rename the `children` property of a scene to `objects`. This aligns it with other things like TileEngine and Pool as `children` should be for structures that create a parent/child relation (like GameObject) whereas `objects` should be used for containers (TileEngine, Pool, Quadtree, etc.).
Also cleaned up duplicate code around removing an item from an array.
BREAKING CHANGE
=> feat(scene): rename children, ddChild, and removeChild to objects, add, and remove (respectively)

src/gameObject.js, src/gesture.js, src/pointer.js, src/quadtree.js, src/scene.js, src/tileEngine.js, test/integration/scene.spec.js, test/typings/gameObject.ts, test/typings/gesture.ts, test/typings/tileEngine.ts, test/unit/gameObject.spec.js, test/unit/gamepad.spec.js, test/unit/gesture.spec.js, test/unit/keyboard.spec.js, test/unit/pointer.spec.js, test/unit/scene.spec.js, test/unit/tileEngine.spec.js
All input APIs are similarly named and take about the same type of parameters. All classes with children / objects have similar add/remove apis and can now all take a single object, an array of objects, or a comma-separated list of objects.
=> chore: make apis consistent

src/kontra.defaults.js, src/kontra.js
Fixes https://github.com/straker/kontra/issues/291
Tested in [my own little repo](https://github.com/burntcustard/kontra-gh-pages-iso-test/blob/main/src/js/main.js) where I've imported TileEngineClass and overridden `TileEngine._r()` to allow isometric rendering (kind of) of tiles
=> Add TileEngineClass to exports

test/unit/gameLoop.spec.js
Fixes an issue where dodgy floating point rounding/addition would result in `GameLoop.update()` (and therefore `done()`) never being called in the `'should update if page is blurred when blur is true'` gameLoop test.
[Discussion is on the Js13kGames Slack](https://js13kgames.slack.com/archives/C018KMA4UUD/p1647273749781259)
There's no issue on GitHub for this - I've gone straight in for a Pull Request - hopefully as it's such a minor change that's okay 😀
=> Fix gameLoop unit test rounding issue

test/unit/kontra.defaults.spec.js, test/unit/kontra.spec.js, test/unit/tileEngine.spec.js
"... and class" is perhaps unnecessary, but not every export test tests classes, so I thought it might be worth specifying.
Unfortunately test code coverage isn't affected by these additions 😂
=> tests: ensure class exports exist for various Kontra exports

src/helpers.js, test/integration/vector.spec.js, test/unit/helpers.spec.js
BREAKING CHANGE: The angle returned from `angleToTarget` no longer applies a quarter rotation to the final angle. Previous calculations to determine x and y from the returned angle will now return the wrong values.
Also updates `movePoint` to handle the change to the angle returned from `angleToTarget`.
Closes #312
=> feat(helper): return correct angle from angleToTarget

src/gamepad.js, test/unit/gamepad.spec.js
I have a scenario where I want to register the same listener for several gamepad buttons. I also want to know which button was pressed, which makes it easier to register 1 event listener, and remove 1 event listener (instead of creating multiple listeners)
AS-IS
It's difficult to make a decision to know which button was pressed inside the callback in `onGamepad`
We have to write code like this, but it only works for one key, not an array of keys
```js
onGamepad('south', onPlayerInput.bind({buttonName:'south'})); // not so pretty, and can be difficult to use correctly.
function onPlayerInput(...args){
console.log('buttonName', this.buttonName});
}
// alternatively
onGamepad('south', (...args) => onPlayerInput(...args,{buttonName:'south'}));
```
TO-BE
Receive the `buttonName` as the third …
=> feat(gamepad): pass buttonName as extra param to gamepad callback

src/core.js, src/gameLoop.js, src/gameObject.js, src/scene.js, src/text.js, src/tileEngine.js, test/integration/core.spec.js, test/setup.js, test/unit/gameLoop.spec.js, test/unit/gameObject.spec.js, test/unit/scene.spec.js, test/unit/text.spec.js, test/unit/tileEngine.spec.js
Use the `init` emit from core to initialize all the `context` properties of various objects.
Closes #318
=> fix: allow objects to be created before init

docs/service-worker.js, gulpfile.js, package-lock.json, package.json, tasks/docs.js, tasks/release.sh
Each release will up the version of the doc cache which should effectively clear the cache for each new release.
Also added the kontra version to the files so you can easily find out what version you're using.
Closes #289
=> chore: add version comment to kontra files, version doc service worker

src/scene.js, test/unit/scene.spec.js
A fix to the Scene object where adding objects with their own DOM nodes before `init` was called would fail since it would try to move the DOM node to the scene's DOM node, which didn't exist yet.
=> chore: fix scene init not creating dom node before adding objects

src/tileEngine.js, test/unit/tileEngine.spec.js
=> fix(tileEngine): prevent negative sx/sy when map size is smaller than canvas size

package.json, test/setup.js, test/unit/animation.spec.js, test/unit/gameLoop.spec.js, test/unit/gameObject.spec.js, test/unit/gamepad.spec.js, test/unit/helpers.spec.js, test/unit/input.spec.js, test/unit/keyboard.spec.js, test/unit/pointer.spec.js, test/unit/scene.spec.js, test/unit/sprite.spec.js, test/unit/spriteSheet.spec.js, test/unit/text.spec.js, test/unit/tileEngine.spec.js, test/unit/updatable.spec.js
Ensure no memory leaking between tests by restoring sinon at root `afterEach` instead of individually in each test
=> test: restore sinon in single place

karma.conf.js, src/helpers.js, src/kontra.defaults.js, src/kontra.js, src/random.js, test/setup.js, test/typings/helpers.ts, test/typings/random.ts, test/unit/helpers.spec.js, test/unit/kontra.defaults.spec.js, test/unit/kontra.spec.js, test/unit/random.spec.js
Random implementation based off [Python random module](https://docs.python.org/3/library/random.html)
* Moved `randInt` and `seedRand` to own file, added `rand` and `getSeed` functions
* `seedRand` no longer returns `rand` as a function but instead just modifies the seed
* `seedRand` accepts a number (or no parameter and defaults to current time)
* updated the `seedRand` string hash function from xfnv1a to MurmurHash3 to reuse `Math.iml` for slightly better compression
* `randInt` accepts a function as 3rd parameter which can be used to pass a function that can bias the random number
* `randInt` uses `rand` by default instead of `Math.random` so is affected by seeding the PRNG
* updated the PRNG to use SplitMix32 algorithm instead of LCG (Lehmer RNG) as …
=> feat(random)!: add random functions rand and getSeed. seedRand no longer returns function and accepts a number

docs/pages/reducing-file-size.js, src/gameObject.js, src/updatable.js, test/typings/gameObject.ts, test/unit/gameObject.spec.js
=> feat(gameObject): add angular velocity and acceleration

src/tileEngine.js, test/unit/tileEngine.spec.js
=> feat(tileEngine): support flipped tiles in Tiled

src/tileEngine.js, test/unit/tileEngine.spec.js
Hello @straker 
The last update about flipping vertically or horizontally don't cover all cases. Indeed, if a tile is rotated 90° clockwise or anticlockwise, Tiled use bits 30.
I implemented that feature. I hope to have carefuly follow your coding style and do the thing the right way. 
I'm open to your feedback about my PR.
regards
@sdeseille
=> Tileengine rotated

src/spriteSheet.js, test/unit/spriteSheet.spec.js
Turns out I forgot to actually default the props to 0 in the code, so not passing them caused the animation to never update.
=> fix(spriteSheet): actually default margin and spacing to 0

src/pointer.js, test/integration/sprite.spec.js, test/unit/pointer.spec.js
When I added the [code to handle sprites as circles](#317) I accidentally created a name collision with the pointer render override function. I also had the same problem in the TIleEngine and [had to change it there as well](https://github.com/straker/kontra/pull/407/files#diff-c13f3e44d0ab1165381f057bf876cfcaa8adc659e1e8fdb26b5610e9a11ed446R688). To prevent this problem in the future I changed the pointer override to a double underscore instead of using a single one as I don't use double underscore for private variables.
=> fix(GameObject): render properly when tracked by pointer
