straker/kontra

docs/api/tileEngine.html

Made it clearer where to put the tileEngine.addLayers code. When I first saw it, I thought I needed to put it after the img.onload function definition.

Connect #add-images code to #add-layers

---

src/pool.js

Just saw a missing word in the doc 😉

Correct missing word in doc

---

docs/index.html

There was a typo, I fixed it.
...Or is it?

Fixed "mirco" typo

---

doc-tasks.js
docs/api/animation.html
docs/api/assets.html
docs/api/events.html
docs/api/keyboard.html
docs/api/plugin.html
docs/api/pool.html
docs/api/quadtree.html
docs/api/sprite.html
docs/api/spriteSheet.html
docs/api/tileEngine.html
docs/api/vector.html
docs/api_docs/plugin.js
docs/api_docs/pool.js
docs/api_docs/quadtree.js
kontra.js
kontra.mjs
src/animation.js
src/assets.js
src/keyboard.js
src/pool.js
src/sprite.js
src/spriteSheet.js
src/tileEngine.js

also update the doc-tasks to lowercase first letter in kontra.* objects to generate correct URLs

Docs: fix broken links

---

examples/event/assetLoaded.html

derived from the depreciated kontra asset loader example.

assetLoaded event example

---

docs/api/pointer.html
src/pointer.js

Fixed misspelled Sprite in docs

---

src/pointer.js
test/unit/pointer.spec.js

fix(pointer): account for border, padding and transform

---

src/pointer.js

docs: track does not accept array

---

src/helpers.js
src/kontra.defaults.js
src/kontra.js
src/pointer.js
src/quadtree.js
src/tileEngine.js
src/utils.js
test/unit/helpers.spec.js
test/unit/kontra.defaults.spec.js
test/unit/kontra.spec.js

Move from utils as it is helpful for anyone, not just internal.

feat(helpers): add getWorldRect

---

src/pointer.js
test/unit/pointer.spec.js

fix(pointer): account for camera

---

src/helpers.js
src/quadtree.js
src/sprite.js
src/spriteSheet.js
test/typings/helpers.ts
test/typings/spriteSheet.ts

Just expanding any `{Object}` types where it makes sense

typescript: specify object properties

---

src/text.js
test/unit/text.spec.js

fix(text): cast text to string

---

test/typings/pool.ts

Seems to work without problems. Not sure why it didn't before.
Closes #207

tests: add ts test for pool create using Sprite

---

src/helpers.js
test/integration/scene.spec.js
test/unit/helpers.spec.js

fix(helpers/getWorldRect): work with tileEngine

---

src/helpers.js
test/typings/helpers.ts

Forgot to add this as part of #215

ts: allow tileEngines for getWorldRect

---

src/grid.js

docs(grid): note that the dir is affected by canvas attribute

---

src/pointer.js
test/unit/button.spec.js
test/unit/pointer.spec.js

feat(pointer): initPointer can change radius

---

src/keyboard.js
test/unit/keyboard.spec.js

feat(keyboard): preventDefault for all bound keys

---

src/keyboard.js
src/utils.js
test/typings/keyboard.ts

fix(utils): update srOnlyStyles

---

src/gameLoop.js
src/utils.js
test/typings/gameLoop.ts
test/unit/gameLoop.spec.js

feat(gameLoop): do not update loop when tab is blurred

---

src/grid.js
test/unit/grid.spec.js

fix(grid): take into account child world width and height

---

src/utils.js
test/unit/button.spec.js
test/unit/scene.spec.js

fix(srOnly): add clip to sr only style

---

src/gameObject.js

fix(sprite): translate by camera position before rotation

---

examples/gesture/gesture.html
src/gesture.js
src/kontra.defaults.js
src/kontra.js
src/pointer.js
test/typings/gesture.ts
test/unit/gesture.spec.js
test/unit/kontra.defaults.spec.js
test/unit/kontra.spec.js
test/unit/pointer.spec.js

feat(gesture): add swipe and pinch gesture support

---

src/gameObject.js
src/grid.js
test/typings/grid.ts
test/unit/gameObject.spec.js
test/unit/grid.spec.js

feat(grid): allow setting alignment for individual rows or cols, allow setting children

---

src/core.js
test/unit/core.spec.js

feat(core): allow contextless environment

---

docs/assets/js/snake.js
examples/galaxian/js/galaxian.js
examples/galaxian/js/index.js
examples/scene/gameScene.js
examples/scene/snake.js
examples/sprite/clampSpriteMovement.html
examples/sprite/controllingASprite.html
examples/tileEngine/camera/index.html
src/keyboard.js
src/kontra.defaults.js
src/kontra.js
test/typings/keyboard.ts
test/unit/gamepad.spec.js
test/unit/keyboard.spec.js
test/unit/kontra.defaults.spec.js
test/unit/kontra.spec.js

feat(keyboard): rename bindKeys to onKey, unbindKeys to offKey

---

examples/pointer/tracking.html
src/button.js
src/gamepad.js
src/gesture.js
src/keyboard.js
src/kontra.defaults.js
src/kontra.js
src/pointer.js
src/scene.js
test/typings/gesture.ts
test/typings/pointer.ts
test/unit/gesture.spec.js
test/unit/kontra.defaults.spec.js
test/unit/kontra.spec.js
test/unit/pointer.spec.js

feat(pointer, gesture): add unregister functions, remove onPointerUp/Down, add onPointer

---

src/helpers.js
src/kontra.defaults.js
src/kontra.js
src/scene.js
test/integration/scene.spec.js
test/typings/helpers.ts
test/unit/helpers.spec.js
test/unit/kontra.defaults.spec.js
test/unit/kontra.spec.js
test/unit/scene.spec.js

feat(scene,helpers): allow scene to sort chlidren. add depthSort helper

---

src/gameObject.js
test/unit/gameObject.spec.js

fix(gameObect): clamp opacity between 0 and 1

---

src/keyboard.js
test/typings/keyboard.ts
test/unit/keyboard.spec.js

feat(keyboard): allow keyPressed to accept array of keys

---

src/vector.js
test/unit/vector.spec.js

fix(vector): handle normalizing zero vector

---

gulpfile.js
src/vector.js
test/permutations/index.js
test/unit/vector.spec.js

feat(vector): add direction function

---

src/vector.js
test/integration/vector.spec.js
test/typings/vector.ts
test/unit/vector.spec.js

feat(vector): add set function and allow initialize with object

---

docs/pages/reducing-file-size.js
gulpfile.js
src/text.js
test/permutations/index.js
test/typings/text.ts
test/unit/text.spec.js

feat(text): add text stroke

---

src/text.js
test/unit/text.spec.js

fix(text): correctly handle string with both newlines and a fixed width

---

docs/api_docs/pool.js

docs(pool): clarify create function requirements

---

src/animation.js
src/sprite.js
src/spriteSheet.js
test/typings/animation.ts
test/unit/animation.spec.js
test/unit/sprite.spec.js

feat(animation): add start and stop functions, isStopped proeprty

---

src/scene.js
src/tileEngine.js
test/integration/scene.spec.js
test/integration/tileEngine.spec.js
test/unit/scene.spec.js
test/unit/tileEngine.spec.js

fix(pointer): correctly track objects when scene/tileEngine camera is moved

---

docs/pages/getting-started.js

Correct Issue #354 , in the right way this time !

docs: update webmaker link

---

tasks/docs.js

Correct the first missing letter in issue #359 
This "bug" was introduced by https://github.com/straker/kontra/commit/a6dfd5c805f5710bb35735be0a5801bc60a7e42f#diff-4d9fabf5cd7efa6a1f77465e768b2a83eb1ae13fb9b93d5ce5cd360ba46944e1L64

docs: update missing first letter

---

README.md

Based on conversation in https://github.com/straker/kontra/issues/368.

Add links to js13kgames slack and gamedev.js discord

---

docs/api_docs/button.js
docs/api_docs/gameObject.js
docs/api_docs/grid.js
src/gameObject.js
src/gamepad.js
src/helpers.js
src/input.js
src/scene.js

Just noticed a few 404s when I was reading the docs.

docs: Fix 404s

---

src/gameLoop.js
test/unit/gameLoop.spec.js

fix(gameLoop): prevent zombie frame when start is called twice

---

package.json
src/button.js
src/scene.js
src/utils.js
test/unit/button.spec.js
test/unit/scene.spec.js

fix: prevent scrolling page on element focus

---

src/gameLoop.js
test/unit/gameLoop.spec.js

fix(gameLoop): emit tick event every update

---

package.json
src/button.js
src/scene.js
src/utils.js
test/unit/utils.spec.js

Also refactors `scrollParams` to `focusParams` as it wasn't named correctely.
Closes #367

chore: fix addToDom selector

---

src/button.js
src/scene.js
test/unit/button.spec.js
test/unit/scene.spec.js

feat(button,scene): expose node property

---

src/button.js
src/utils.js
test/unit/button.spec.js

feat(button): allow adding the HTMLButton element to a container

---

src/tileEngine.js
test/typings/tileEngine.ts
test/unit/tileEngine.spec.js

Closes https://github.com/straker/kontra/issues/355

feat(tileEngine): add getPosition function
